### ISSUE TITLE
Fatal error: Call to undefined method ezSQL_mysql::fetchObjects() 

### ISSUE THREAD

**Issue by bavaughan** [YOURLS/mass-remove-links#2]
yourls v1.6.  Works as expected.  I installed "Mass Remove Links 1.1" and activated successfully.  

If I select a range of documents to delete, I get the error:
**Fatal error: Call to undefined method ezSQL_mysql::fetchObjects() in D:\htdocs\yourls\user\plugins\mass-remove-links\plugin.php on line 123**

If I UNcheck "Display results, do not delete. This is a test", I get the error
**Fatal error: Call to undefined method ezSQL_mysql::fetchAffected() in D:\htdocs\yourls\user\plugins\mass-remove-links\plugin.php on line 146**

Environment:
yourls v1.6
Mass Remove Links 1.1
PHP Version 5.4.15
Apache 2.4.4
MySQL 5.6.11

**Comment by ozh** [comment]
https://github.com/YOURLS/mass-remove-links/releases

**Comment by ozh** [comment]
Your YOURLS is way outdated, dude (1.6 was released in 2013 !!)
